[package]
name = "git-statistic"
version = "0.0.8"
description = "Git Statistics Tools"
authors = ["lsk"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

log = "^0.4"
base64 = "0.21.5"
anyhow = "1.0"
percent-encoding = "2.3.0"
chrono = "0.4.31"
# tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }

image = "0.24.7"
tokio = { version = "1.27.0", features = ["full", "tracing"] }
colorsys = { version = "*", default-features = false }
dirs = "5.0"
uuid = { version = "1.4.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
num = "0.4"
rusqlite = { version = "0.32.1", features = ["bundled"] }
r2d2_sqlite = "0.25.0"
r2d2 = "0.8.10"
rayon = "1.10.0"
serde_repr = "0.1.17"
openssl-sys = { version = "0.9", features = ["vendored"] }

git2 = { version = "0.18.1", features = ["vendored-libgit2"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-log = "2.0.1"
time = "0.3.36"
[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

# Optimized for bundle size. If you want faster builds comment out/delete this section.
[profile.release]
lto = true        # Enable Link Time Optimization
opt-level = "z"   # Optimize for size.
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
strip = true      # Automatically strip symbols from the binary.
debug = false


[env]
STATIC_VCRUNTIME = false

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"
